Update README
orbitdb/orbit-bot pull request #3
Opened 2019-01-16 18:02 UTC by adam-palazzo

This updates the README to the orbitdb repo standards, changed dates on licenses

2019-01-16 18:26 UTC, RichardLitt requested changes
Close.

2019-01-16 18:26 UTC, RichardLitt commented on README.md
> +# <Orbit Bot>
Remove brackets.

2019-01-16 18:26 UTC, RichardLitt commented on README.md
> +[![npm version](https://badge.fury.io/js/<orbit-bot>.svg)](https://www.npmjs.com/package/<orbit-bot>)
The brackets in `<Replace>` are also meant to removed.

2019-01-16 18:26 UTC, RichardLitt commented on README.md
> -**WIP**
Keep this here. Maybe add:

`Status: **WIP**`.

2019-01-16 18:26 UTC, RichardLitt commented on README.md
> +npm i <orbit-bot>
Again, no brackets. And is this on NPM?

2019-01-16 18:26 UTC, RichardLitt commented on README.md
> +This is a WIP but feel free to submit a PR! You can reach us [on Gitter](https://gitter.im/orbitdb/Lobby), or in the [issues section](https://github.com/orbitdb/<orbit-bot>/issues).
Say open an issue before opening a PR. WIP means more hand-holding for contribs.

2019-01-16 18:26 UTC, RichardLitt commented on README.md
> +This is a WIP but feel free to submit a PR! You can reach us [on Gitter](https://gitter.im/orbitdb/Lobby), or in the [issues section](https://github.com/orbitdb/<orbit-bot>/issues).
Remove brackets.

2019-01-16 18:26 UTC, RichardLitt commented on README.md
> +[MIT](LICENSE) © 2016-2019 Haja Networks Oy
This needs to reflect the license file.

2019-01-16 18:27 UTC, RichardLitt commented
Also, update the Code of Conduct. This version is old.

2019-01-16 21:24 UTC, RichardLitt requested changes
Thanks Adam.

2019-01-16 21:24 UTC, RichardLitt commented on README.md
> +# Orbit Bot
I'd prefer to keep the name as is, in general.

2019-01-16 21:24 UTC, RichardLitt commented on README.md
> +[![node](https://img.shields.io/node/v/orbit-bot.svg)](https://www.npmjs.com/package/orbit-bot)
The link doesn't match the badge? What is the node badge doing?

2019-01-16 21:24 UTC, RichardLitt commented on README.md
> +## Status: WIP
Nope: Just:

```md

Status: **WIP**

```

2019-01-16 21:24 UTC, RichardLitt commented on README.md
> +This project [nodejs](https://nodejs.org/).
Uses?

2019-01-16 21:24 UTC, RichardLitt commented on LICENSE
> +Copyright (c) 2018-2019 Haja Networks Oy
Per new company policy, stop updating years and don't touch them anymore.

2019-01-16 21:24 UTC, RichardLitt commented on README.md
> +We also have **regular community calls**, which we announce in the issues in [the @orbitdb welcome repository](https://github.com/orbitdb/welcome/issues). Join us!
Change (everywhere) from @orbitdb to @OrbitDB. Seems nicer.

2019-01-16 21:24 UTC, RichardLitt commented on README.md
> +We also have **regular community calls**, which we announce in the issues in [the @orbitdb welcome repository](https://github.com/orbitdb/welcome/issues). Join us!
Whoa! GitHub changes it to lowercase. Uh. Scratch that, I guess? Fascinating. Maybe we should stop doing this everywhere.

2019-01-16 21:24 UTC, RichardLitt commented on README.md
> +[MIT](LICENSE) © 2016-2018 Protocol Labs Inc., © 2018-2019 Haja Networks Oy
As above, don't change the year. Also, don't add another copyright symbol - one is enough.

2019-01-16 21:24 UTC, RichardLitt commented on package.json
> +    "adam-palazzo"
Run `git authors`. Is there another contributor we should add here? (Note: then remove Authors, don't commit the file that is created in the repo.)

2019-01-18 17:06 UTC, adam-palazzo commented on README.md
> +We also have **regular community calls**, which we announce in the issues in [the @orbitdb welcome repository](https://github.com/orbitdb/welcome/issues). Join us!
I wondered why this kept popping up, I swore I was triple checking every time :+1:

2019-01-18 19:27 UTC, RichardLitt commented on CODE_OF_CONDUCT.md
> +is deemed necessary and appropriate to the circumstances. The project team is# Contributor Covenant Code of Conduct
What's going on here?

2019-01-18 19:28 UTC, RichardLitt commented on README.md
> +This project [nodejs](https://nodejs.org/).
Still needs uses.

2019-01-18 19:28 UTC, RichardLitt commented on package.json
> -  "author": "Haad",
Keep.

2019-01-18 19:28 UTC, RichardLitt requested changes
Smaller changes.

2019-01-18 23:24 UTC, adam-palazzo commented on README.md
> +This project [nodejs](https://nodejs.org/).
Done!

2019-01-18 23:26 UTC, adam-palazzo commented on CODE_OF_CONDUCT.md
> +is deemed necessary and appropriate to the circumstances. The project team is# Contributor Covenant Code of Conduct
Not sure, fixed it though

2019-01-18 23:42 UTC, RichardLitt commented on CODE_OF_CONDUCT.md
> +is deemed necessary and appropriate to the circumstances. The project team is# Contributor Covenant Code of Conduct
Still doubled.

2019-01-18 23:51 UTC, adam-palazzo commented on CODE_OF_CONDUCT.md
> +is deemed necessary and appropriate to the circumstances. The project team is# Contributor Covenant Code of Conduct
I see what was going on. Actually fixed it

2019-01-19 00:10 UTC, merged

2019-01-19 00:11 UTC, RichardLitt commented
Danke.